version: '3'
services:
  apache:
    container_name: coffee_shop_apache
    image: webdevops/apache:ubuntu-16.04
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
      WEB_ALIAS_DOMAIN: rcoa.localhost
      WEB_PHP_SOCKET: php-fpm:9000
    volumes: # Only shared dirs to apache (to be served)
      - ./:/var/www/
    networks:
      - network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
  php-fpm:
    container_name: coffee_shop_php
    image: cyberduck/php-fpm-laravel:8.0
    volumes:
      - ./:/var/www/
      - ./vendor:/var/www/vendor:delegated
      - ./storage:/var/www/storage:delegated
      - ./node_modules:/var/www/node_modules:cached
    networks:
      - network
  db:
    container_name: coffee_shop_db
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    ports:
      - "33060:3306"
volumes:
  db_data:
    driver: "local"
networks:
  network:
    driver: "bridge"
